package main

type Kaomoji struct {
  name string
  kaomoji string
  keywords string
}

var kaomojis = []*Kaomoji{
  {"rage_face", "ლ(ಠ益ಠ)ლ", "rage_face,rage,face"},
  {"capital_building", "๑۩۩๑", "capital_building,capital,building"},
  {"love_you", "ᵛᵉᵧₒᵤᶫᵒᵛᵉᵧₒᵤ ᶫᵒᵛᵉᵧₒᵤ", "love_you,love,you"},
  {"cat", "=^..^=", "cat,cat"},
  {"monocle", "(╭ರ_•́)", "monocle,monocle"},
  {"flower_girl", "(づ🌺￣ ³￣)づ", "flower_girl,kisses,cute,flower,girl"},
  {"kiss_love", "σ(≧ε≦σ) ♡", "kiss_love,kiss,heart,love,affection,chu"},
  {"smooth", "(づ ￣ ³￣)づ ⓈⓂⓄⓄⓉⒽ", "smooth,smooth"},
  {"hug_for_you", "HUG FOR YOU~╰(*´︶`*)╯(´・ω・｀)", "hug_for_you,hug,hug you,sweet,comfort,love"},
  {"swimming_left_fish", "(°)#))<<", "swimming_left_fish,fish,swim,water"},
  {"sparkle", "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", "sparkle,sparkle"},
  {"needle", "┣▇▇▇═─", "needle,needle"},
  {"crowd_2", "༼ ºل͟º༼ ºل͟º ༽ºل͟º ༽", "crowd_2,crowd,2"},
  {"guitar", "c====(=#O| )", "guitar,guitar"},
  {"delicious", "(*´ڡ`●)", "delicious,delicious,yummy,food,eat"},
  {"blank", ": ◉ ∧ ◉ : ╏", "blank,blank"},
  {"deal_with_it", "( •_•)>⌐■-■ (⌐■_■)", "deal_with_it,deal,with,it"},
  {"happily_flip_tables", "┻━┻ ︵ ლ(⌒-⌒ლ)", "happily_flip_tables,happily,happy,jolly,flip,tables"},
  {"ffffggh", "-)9)-5546{{}]]]]]", "ffffggh,ffffggh"},
  {"kita", "ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!", "kita,kita"},
  {"round_cat", "~(^._.)", "round_cat,round,cat"},
  {"cute_flower_bear", "(✿◕㉨◕)", "cute_flower_bear,bear,animal,cute,pet,flower"},
  {"rock_on", "\\m/ (>.<) \\m/", "rock_on,rock,on"},
  {"caterpillar", "(,(,(,(,(,(,(,(, \")", "caterpillar,caterpillar"},
  {"kiss_star", "☆⌒ヽ(*'､^*)chu", "kiss_star,kiss,chu,love,affection,shy"},
  {"pac_man", "ᗧ···ᗣ···ᗣ··", "pac_man,pac,man"},
  {"energy", "つ ◕_◕ ༽つ  つ ◕_◕ ༽つ", "energy,energy"},
  {"bow", "o(_ _)o", "bow,bow"},
  {"indeed", "ಠ_ರೃ", "indeed,indeed"},
  {"omg_yes", "(๑˃̵ᴗ˂̵)و", "omg_yes,omg,yes"},
  {"hands_up_indifference", "┐(￣∀￣)┌", "hands_up_indifference,indifference,apathy,insensitivity,disdain"},
  {"table_flip_angry", "(┛✧Д✧))┛彡┻━┻", "table_flip_angry,table flip,angry,what?!,shocked"},
  {"dgaf", "┌∩┐(◣ _ ◢)┌∩┐", "dgaf,dgaf"},
  {"could_not_find_items_that_match_search_term.", "ʕノ•ᴥ•ʔノ ︵ ┻━┻", "could_not_find_items_that_match_search_term.,could,not,find,items,that,match,search,term."},
  {"wat-wat", "Σ(‘◉⌓◉’)", "wat-wat,wat-wat"},
  {"dance", "ᕕ(⌐■_■)ᕗ ♪♬", "dance,dance"},
  {"spider", "/X\\(-)/X\\", "spider,spider"},
  {"octoshrug", "ʅ(°_°)ʃ", "octoshrug,octopus,shrug,squid"},
  {"exchange", "(╯°□°）╯︵ ǝƃuɐɥɔxǝ", "exchange,exchange"},
  {"sympathy", "(ノ_<。)ヾ(´▽｀)", "sympathy,cry,kindness,affinity,compassion"},
  {"crab", "(\\|) ._. (|/)", "crab,crab"},
  {"sad_lenny", "( ͡° ʖ̯ ͡°)", "sad_lenny,sad,lenny"},
  {"zoidberg", "(\\/) (;,,;) (\\/)", "zoidberg,zoidberg"},
  {"cute_polar_bear", "ʕ •ᴥ• ʔ", "cute_polar_bear,bear,polar bear,smile bear"},
  {"fight_enemies", "(｀⌒*)O-(｀⌒´Q)", "fight_enemies,quarrel,punch_in_face,angry,beat,unhappy"},
  {"sniff", "(´＿｀。) *sniff*", "sniff,sad,unhappy,sniff,cry,depressed,feeling down"},
  {"flower_cat", " /ᐠ｡ꞈ｡ᐟ✿\\ ", "flower_cat,cat,flower,nya,meow,pet,cute"},
  {"wtf_dude?", "＼(◑д◐)＞∠(◑д◐)", "wtf_dude?,wtf,dude?"},
  {"snowing", "✲´*。.❄¨¯`*✲。❄。*。", "snowing,snowing"},
  {"butterfly", "Ƹ̵̡Ӝ̵̨̄Ʒ", "butterfly,butterfly"},
  {"high_five", "( ⌒o⌒)人(⌒-⌒ )v", "high_five,high,five"},
  {"flip_table", "(╯°□°）╯︵ ┻━┻", "flip_table,flip,table"},
  {"tears", "꒰๑•̥﹏•̥๑꒱", "tears,cry,vertical tears,failed,unhappy"},
  {"upc", "║▌║█║▌│║▌║▌█", "upc,upc"},
  {"disapproving_bear_with_outstretched_arms_flipping_table", "ʕつಠᴥಠʔつ ︵ ┻━┻", "disapproving_bear_with_outstretched_arms_flipping_table,disapproving,bear,with,outstretched,arms,flipping,table"},
  {"pig", "^(*(oo)*)^", "pig,pig"},
  {"barbell", "❚█══█❚", "barbell,barbell"},
  {"y_u_no", "ლ(ಠ_ಠლ)", "y_u_no,y,u,no"},
  {"fish", "><((((`>", "fish,fish"},
  {"ping_pong", "( _)0*´¯`·.¸.·´¯`°Q(_ )", "ping_pong,ping,pong"},
  {"shocked", "(∩╹□╹∩)", "shocked,shocked"},
  {"exciting", "o(≧∇≦o)", "exciting,exciting,circle hands,happy,joy"},
  {"hit", "█▬█ █ ▀█▀", "hit,hit"},
  {"derp", "ヘ（。□°）ヘ", "derp,derp"},
  {"squee", "ヾ(◎o◎,,；)ﾉ", "squee,squee"},
  {"cassette", "[●▪▪●]", "cassette,cassette"},
  {"surprise_round_eyes", "∑(O_O;)", "surprise_round_eyes,surprised,shocked,curious"},
  {"singing_2", "d(^o^)b¸¸♬", "singing_2,singing"},
  {"die", "[::]", "die,die"},
  {"myancat", "mmmyyyyy<⦿⽘⦿>aaaannn", "myancat,myancat"},
  {"gun", "▄︻̷̿┻̿═━一", "gun,gun"},
  {"hugme", "／人 ⌒ ‿‿ ⌒ 人＼", "hugme,hugme"},
  {"why?!", "ლ( `Д’ ლ)", "why?!,why?!"},
  {"thank_you", "*:;,｡･★Thanks(◎≧v≦)人(≧v≦●)Thanks☆･:.,;*", "thank_you,thanks,thx,gratitude"},
  {"thumbs_down", "p(●｀□´●)q", "thumbs_down,thumb_down,angry,unhappy"},
  {"hu_hu", "█▬█ █▄█ █▬█ █▄█", "hu_hu,hu,hu"},
  {"fox", "-^^,--,~", "fox,fox"},
  {"porcupine", "(•ᴥ• )́`́'́`́'́⻍", "porcupine,porcupine"},
  {"love", "(♥_♥)", "love,love"},
  {"friends_hand_in_hand", "ヽ(≧◡≦)八(o^ ^o)ノ", "friends_hand_in_hand,friends,hangout,cheer,together,happy,smile"},
  {"cheering", "\\\\\\(۶•̀ᴗ•́)۶//／／", "cheering,happy,cheer,joy,hands up"},
  {"boobs", "( . Y . )", "boobs,boobs"},
  {"council_of_doubt", "ʕಠಿᴥಠʔ ಠಿ_ಠ ᶘಠಿᴥಠᶅ", "council_of_doubt,council,of,doubt"},
  {"drowning", "人人人ヾ( ;×o×)〃 人人人", "drowning,drowning"},
  {"jailed_smile", "||Φ|(|ﾟ|∀|ﾟ|)|Φ||", "jailed_smile,jailed,shut in"},
  {"fingers", "┌∩┐(◣_◢)┌∩┐", "fingers,fingers"},
  {"haters_gonna_hate", "ᕕ( ᐛ )ᕗ", "haters_gonna_hate,haters,gonna,hate"},
  {"nope", "t(-_-t)", "nope,nope"},
  {"header", "", "header,header"},
  {"shot_you", "(ﾒ￣▽￣)︻┳═一", "shot_you,shooting,weapon,fight,war,gun"},
  {"wizard", "(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ. *", "wizard,wizard"},
  {"happy_Xmas", "o＜(*’v`p)p☆+*:;;;:*+☆ Happy Xmas ☆+*:;;;:*+☆q(q’v`*)＞o", "happy_Xmas,merry christmas,christmas time,christmas,Xmas"},
  {"neo", "(⌐■_■)--︻╦╤─ - - -", "neo,neo"},
  {"gimme", "༼ つ ◕_◕ ༽つ", "gimme,gimme,give,reach,take,have"},
  {"playing_in_snow", "(╯^□^)╯︵ ❄☃❄", "playing_in_snow,playing,in,snow"},
  {"victory!", "V(-.o)V", "victory!,victory!"},
  {"majic_star", "(ﾉ≧∀≦)ﾉ ‥…━━━★", "majic_star,majic,star,shooting,biu-biu"},
  {"blushing_flower_girl", "(///∇///✿)", "blushing_flower_girl,blushing,girl,flower,shy,cute"},
  {"man_spider", "/╲/\\༼ *ಠ 益 ಠ* ༽/\\╱\\", "man_spider,man,spider"},
  {"bear_putting_on_glasses", "ʕつ•ᴥ•ʔつ⌐■-■", "bear_putting_on_glasses,bear,putting,on,glasses"},
  {"yessir", "∠(･`_´･ )", "yessir,yessir"},
  {"afraid", "(\u3000ﾟ Дﾟ)", "afraid,afraid"},
  {"trick", "+1 @skardude", "trick,trick"},
  {"sad_donger", "ヽ༼ຈʖ̯ຈ༽ﾉ", "sad_donger,sad,donger"},
  {"dog", "ˁ˚ᴥ˚ˀ", "dog,dog"},
  {"dumbbell", "❚█══█❚", "dumbbell,dumbbell"},
  {"singing", "((ヽ(๑╹◡╹๑)ﾉ))♬", "singing,music,sing,party,relax"},
  {"nya_cat", "( =ω=)..nyaa", "nya_cat,nya,cat,pet"},
  {"council_of_disapproval", "ʕಠᴥಠʔ ಠ_ಠ ᶘಠᴥಠᶅ", "council_of_disapproval,council,of,disapproval"},
  {"don_fuller", "╭∩╮(Ο_Ο)╭∩╮", "don_fuller,don,fuller"},
  {"fight_me", "(ง︡-︠)ง", "fight_me,fight,me"},
  {"punch", "(o￣∇￣)=◯)`ν゜)", "punch,punch in face,punch you"},
  {"exciting_right", "(/^▽^)/", "exciting_right,exciting,right,hands up,happy"},
  {"thank_you_so_much", "Thank you…(´人｀●)SOOOOO━━＼(´∀｀●)／━━MUCH!!", "thank_you_so_much,thanks,thank you,thanks a lot"},
  {"test", "dasdasd", "test,test"},
  {"sophie", "<XX\"\"\"\"XX>", "sophie,sophie"},
  {"flip_all_tables", "┻━┻︵ \\(°□°)/ ︵ ┻━┻", "flip_all_tables,flip,all,tables"},
  {"arrow", "»»---------------►", "arrow,arrow"},
  {"love_eyes", "(✿ ♥‿♥)", "love_eyes,love,like,loving eyes,smile"},
  {"cat_star", "(=ↀωↀ=)✧", "cat_star,cat,cute,pet"},
  {"friends_together", "٩(๑･ิᴗ･ิ)۶٩(･ิᴗ･ิ๑)۶", "friends_together,friends,hangout,play,party"},
  {"food", "Fooooood…ԅ(¯﹃¯ԅ)", "food,delicious,hungry,yum,salivate"},
  {"cthulhu", "^(;,;)^", "cthulhu,cthulhu"},
  {"punch_2", "O=(-Q)", "punch_2,punch"},
  {"rare", "┌ಠ_ಠ)┌∩┐ ᶠᶸᶜᵏ♥ᵧₒᵤ", "rare,rare"},
  {"polar_bear", "ʕ·͡ᴥ·ʔ", "polar_bear,polar,bear"},
  {"snail", "@_'-'", "snail,snail"},
  {"angry_hug", "(つ◉益◉)つ", "angry_hug,angry,hug"},
  {"jazz_musician", "ヽ(⌐■_■)ノ♪♬", "jazz_musician,jazz,musician"},
  {"oh_hi!", "┬┴┬┴┤･ω･)ﾉ├┬┴┬┴", "oh_hi!,oh,hi!"},
  {"kisses", "(づ ￣ ³￣)づ", "kisses,kisses"},
  {"spooky", "‹’’›(Ͼ˳Ͽ)‹’’›", "spooky,spooky"},
  {"flip_off", "(ಠ_ಠ)┌∩┐", "flip_off,flip,angry,off"},
  {"stick_up_your_dukes", "(ง︡’-‘︠)ง", "stick_up_your_dukes,stick,up,your,dukes"},
  {"squid", "くコ:彡", "squid,squid"},
  {"what????", "(Ͼ˳Ͽ)..!!!", "what????,what????"},
  {"bautista", "(╯°_°）╯︵ ━━━", "bautista,bautista"},
  {"mega_rage", "＼＼\\\\٩(๑`^´๑)۶//／／", "mega_rage,mega,rage"},
  {"crowd", "(-(-_(-_-)_-)-)", "crowd,crowd"},
  {"cheers", "( ^\u200b_^）o自自o（^_\u200b^ )", "cheers,cheers"},
  {"dunno", "٩(͡๏̯͡๏)۶", "dunno,dunno"},
  {"round_bird", ",(u°)>", "round_bird,round,bird"},
  {"airplane", "✈", "airplane,airplane"},
  {"robot", "d[o_0]b", "robot,robot"},
  {"emo", "(///_ ;)", "emo,emo"},
  {"cat_shock", "(ↀДↀ)⁼³₌₃", "cat_shock,cat,cute,pet,angry"},
  {"happy_love", "(≧◡≦) ♡", "happy_love,smile,happy,joy,right heart"},
  {"epic_win", "＼\\ ٩( ᐛ )و /／", "epic_win,epic,win"},
  {"bear_with_outstretched_arms", "ʕつ•ᴥ•ʔつ", "bear_with_outstretched_arms,bear,with,outstretched,arms"},
  {"sunglasses", "(•_•)>⌐■-■ (⌐■_■)", "sunglasses,sunglasses"},
  {"confusion_@eyes", "(＠_＠)", "confusion_@eyes,donno,confused,doubt,question"},
  {"gross_creepy", "༼;´༎ຶ \u06dd ༎ຶ༽", "gross_creepy,gross,creepy,wtf"},
  {"jake", "ˁ(OᴥO)ˀ", "jake,jake"},
  {"angry_face", "(⋟﹏⋞)", "angry_face,angry,face"},
  {"face_palm", "(>ლ)", "face_palm,face,palm"},
  {"riot", "୧༼ಠ益ಠ༽୨", "riot,riot"},
  {"joy", "n_n", "joy,joy"},
  {"table_flip", "(╯°□°）╯︵ ┻━┻", "table_flip,table,flip,anger,angry"},
  {"unicorn", "--'\",---,~", "unicorn,unicorn"},
  {"lenny", "( ͡° ͜ʖ ͡°)", "lenny,lenny"},
  {"hoxom", "h(o x o )m", "hoxom,hoxom"},
  {"lodash_flip", "(╯°□°）╯︵ ɥsɐpoן", "lodash_flip,lodash,flip"},
  {"shrug", "¯\\_(ツ)_/¯", "shrug,shrug"},
  {"tie_fighter", "|-o-|", "tie_fighter,tie,fighter"},
  {"big_black_eyes_bird", "(◉Θ◉)", "big_black_eyes_bird,bird,black round eyes,fly"},
  {"it's_cool_bro", "༼ つ ▀̿_▀̿ ༽つ", "it's_cool_bro,it's,cool,bro"},
  {"mouse", "----{,_,\">", "mouse,mouse"},
  {"table_flip_angry2", "(ノಠ益ಠ)ノ彡┻━┻", "table_flip_angry2,table flip,angry,what?!,shocked"},
  {"im_going_for_a_walk", "ᕕ( ᐛ )ᕗ", "im_going_for_a_walk,im,going,for,a,walk"},
  {"dice", "[::] [::]", "dice,dice"},
  {"bear_flip_table", "ʕノ•ᴥ•ʔノ ︵ ┻━┻", "bear_flip_table,bear,flip,table"},
  {"panda", "ヽ(￣(ｴ)￣)ﾉ", "panda,panda"},
  {"sleepy_coffee", "( -_-)旦~", "sleepy_coffee,sleepy,coffee"},
  {"put_table_back", "┏━┓ ︵ /(^.^/)", "put_table_back,put,table,back"},
  {"salesforce", "(╯°□°）╯︵ ǝɔɹoɟsǝlɐS", "salesforce,salesforce"},
  {"error", "(╯°□°)╯︵ ɹoɹɹƎ", "error,error"},
  {"sorry", "ヾ(_ _。）", "sorry,sorry"},
  {"hadouken", "༼つಠ益ಠ༽つ ─=≡ΣO))", "hadouken,hadouken"},
  {"this_guy", "(☞ﾟ∀ﾟ)☞", "this_guy,this,guy"},
  {"apologize", "m(_ _;m)", "apologize,sorry,I am wrong,confess"},
  {"good_night", "Good(*´ -`)(´- `*)Night", "good_night,good night,night,dream"},
  {"sword_2", "▬▬ι═══════>", "sword_2,sword,2"},
  {"hands_up_greeting", "(⌒ω⌒)ﾉ", "hands_up_greeting,greeting,hello,morning,what's up,hand up,smile,cat mouth"},
  {"happy_rabbit", "／(≧ x ≦)＼", "happy_rabbit,rabbit,exciting,joy"},
  {"love_letter", "I Love You..〆(・∀・＊)", "love_letter,love,writing,valentine,I love you"},
  {"kitty", "=^..^=", "kitty,kitty"},
  {"nathan", "♪└(￣◇￣)┐♪", "nathan,nathan"},
  {"sad", "(っ- ‸ – ς)", "sad,painful,injuried,sick"},
  {"square_mouth_afraid", "＼(º □ º l|l)/", "square_mouth_afraid,afraid,shocked,fear,hands up"},
  {"hello", "(●っゝω・)っ～☆HELLO☆", "hello,hi,what's up,hey"},
  {"shoot", "(◕_◕)=ε/̵͇̿̿/'̿'̿ ̿", "shoot,shoot"},
  {"chu", "(´ε｀ )", "chu,chu"},
  {"crayons", "((̲̅ ̲̅(̲̅C̲̅r̲̅a̲̅y", "crayons,crayons"},
  {"point", "(☞ﾟヮﾟ)☞", "point,point"},
  {"metal", "\\m/_(>_<)_\\m/", "metal,metal"},
  {"winking_star", "(^_<)〜☆", "winking_star,winking,star,cute,trick,joke"},
  {"nosebleeding", "(＾་།＾)", "nosebleeding,shocked,nose,blood,sexy,beautiful"},
  {"simple_dog", "▼・ᴥ・▼", "simple_dog,dog,animal,bark,pet"},
  {"code_eyes", "<  (  o  )  >       </  (  o  )  >", "code_eyes,code,eyes,face"},
  {"bomb", "!!(\u3000’ ‘)ﾉﾉ⌒●~*", "bomb,bomb"},
  {"sniper", "︻デ┳═ー", "sniper,sniper"},
  {"race_car", "\\ō͡≡o˞̶", "race_car,race,car"},
  {"wat", "ಠ_ಠ", "wat,wat"},
  {"ffuuu", "ೕ(Ò⺫ Ó )೨", "ffuuu,ffuuu"},
  {"mac", "\uf8ff", "mac,mac"},
  {"cigar", "(\\\\\\\\\\\\\\| ~~~", "cigar,cigar"},
  {"creep_bear_with_outstretched_arms", "ʕつ ͡°ᴥ ͡°ʔつ", "creep_bear_with_outstretched_arms,creep,bear,with,outstretched,arms"},
  {"dead_eyes", "¿ⓧ_ⓧﮌ", "dead_eyes,dead,eyes"},
  {"coffee_now", "{zzz}°°°( -_-)>c[_]", "coffee_now,coffee,now"},
  {"butt", "(‿|‿)", "butt,butt"},
  {"running_fast", "C= C= C= C=┌(｀ー´)┘", "running_fast,run,escape,right"},
  {"normal_pig", "｡ﾟ(ﾟ´(00)`ﾟ)ﾟ｡", "normal_pig,pig,cute,pork"},
  {"cries", "(╯︵╰,)", "cries,cries"},
  {"wtf_why", "(｢๑•₃•)｢ ʷʱʸ?", "wtf_why,wtf,why"},
  {"satan", "↑_(ΦwΦ;)Ψ", "satan,satan"},
  {"spell_cast", "╰( ⁰ ਊ ⁰ )━☆ﾟ.*･｡ﾟ", "spell_cast,spell,cast"},
  {"set_table", "┣ﾍ(^▽^ﾍ)Ξ(ﾟ▽ﾟ*)ﾉ┳━┳ There we go~♪", "set_table,table,there we go,happy,party,prepare"},
  {"peace", "(‾⌣‾)♉", "peace,peace"},
  {"meditation", "‿( ́ ̵ _-`)‿", "meditation,meditation"},
  {"coffee", "c[_]", "coffee,coffee"},
  {"glasses", "ᒡ◯ᵔ◯ᒢ", "glasses,glasses"},
  {"piggy", "(∩◕(oo)◕∩)", "piggy,piggy"},
  {"bird", "~(‾▿‾)~", "bird,bird"},
  {"sleepy", "(￣ρ￣)..zzZZ", "sleepy,sleeping,tired,exhausted,slobber"},
  {"rose", "@--`--,---", "rose,rose"},
  {"bear_with_doubting_eyes", "ʕಠಿᴥಠʔ", "bear_with_doubting_eyes,bear,with,doubting,eyes"},
  {"rise_and_shine", "(*^｡^*)Rise (*^o^*)And ＼(*^0^*)／Shineｰ!!", "rise_and_shine,morning,get up,rise,shine"},
  {"pancakes?", "( ^-^)_旦", "pancakes?,pancakes?"},
  {"shy_blush", "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)", "shy_blush,shy,blush,love"},
  {"thank_kiss", "Thank CHU♪(‘εﾟ人)*.+゜", "thank_kiss,kiss,chu,thanks,thank you,gratitude"},
  {"dongers", "ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ", "dongers,dongers"},
  {"fix_table", "(ヘ･_･)ヘ┳━┳", "fix_table,fix,table"},
  {"canoe", "~~~~╘══╛~~~~", "canoe,canoe"},
  {"merry_x'mas", "†+☆;:*:;☆。:.†Merry X’mas゜†.:。☆;:*:;☆+†", "merry_x'mas,merry christmas,christmas time,christmas"},
  {"angry_flipped_table", "(づ ò ___ ó )づ ┻━┻", "angry_flipped_table,table,flip,lesson,take that,anger,angry"},
  {"binding_of_isaac", "(¡ ¡)", "binding_of_isaac,binding,of,isaac"},
  {"flex", "ᕙ(⇀‸↼‶)ᕗ", "flex,flex"},
  {"penis", "8===D", "penis,penis,dick,cock"},
  {"hail_satan", "↑_(ΦwΦ;)Ψ", "hail_satan,hail,satan"},
  {"mini_penis", "=D", "mini_penis,mini,penis,dick,cock"},
  {"koala", "@( * O * )@", "koala,koala"},
  {"zombie", "[¬º-°]¬", "zombie,zombie"},
  {"let's_go", "─=≡Σ((( つ•̀ω•́)つLET’SGO!", "let's_go,go,hangout,exciting"},
  {"good_morning", "(*´0)ゞ*yawn* morning~", "good_morning,yawn,morning,greeting"},
  {"joint", "<\\\\\\\\\\\\\\\\> ~~~~", "joint,joint"},
  {"owo", "owo", "owo,owo"},
  {"fungry", "Σ_(꒪ཀ꒪」∠)_", "fungry,fungry"},
  {"camera", "[◉\"]", "camera,camera"},
  {"fuckall", "╭∩╮（︶︿︶）╭∩╮", "fuckall,fuckall"},
  {"chocolate_valentine", "Chocolate!( ・∀・)っ■", "chocolate_valentine,love,chocolate,valentine,I love you"},
  {"blow_me", "ₒ₍₊˒₃˓₎ₒ▁▂▃▅▆▓▒░✩⃛", "blow_me,blow,me"},
  {"bear_with_glasses", "ʕ⌐■ᴥ■ʔ", "bear_with_glasses,bear,with,glasses"},
  {"manatee", "(◕(' 人 ') ◕)", "manatee,manatee"},
  {"oh_you", "(n˘v˘•)¬", "oh_you,oh,you"},
  {"kyle", "♥♥ˁ(⦿ᴥ⦿)ˀ♥♥", "kyle,kyle"},
  {"headphones", "d[-_-]b", "headphones,headphones"},
  {"awkward_cross_eyes", "(´◑ω◐`)", "awkward_cross_eyes,awkward,funny,weird,idiot"},
  {"sniper_rifle", "︻デ┳═ー", "sniper_rifle,sniper,rifle"},
  {"laughing", "(＾▽＾)", "laughing,laughing"},
  {"shark_attack", "~~~~~~\\o/~~~~~/\\~~~~~", "shark_attack,shark,attack"},
  {"writing_quietly", "__φ(．．)", "writing_quietly,writing,study,essay,working hard"},
  {"almost_cared", "╰╏ ◉ 〜 ◉ ╏╯", "almost_cared,almost,cared"},
  {"i'm_out", "X‿X", "i'm_out,i'm,out"},
  {"fail", "o(╥﹏╥)o", "fail,fail"},
  {"smile_with_heart", "(*˘︶˘*).｡.:*♡", "smile_with_heart,smile,joy,heart,love,right heart"},
  {"normal_dog_ear_down", "∪･ω･∪", "normal_dog_ear_down,dog,dog ear down"},
  {"rage", "ლ(ಠ益ಠ)ლ", "rage,rage"},
  {"sailor_moon", "/¯\\_/°^_^°\\_/¯\\", "sailor_moon,sailor,moon"},
  {"kilroy", "ɯ-(ꞋʊꞋ)-ɯ", "kilroy,kilroy"},
  {"council_of_approval", "(/◕ヮ◕)/ (^o^) (✿◠‿◠)", "council_of_approval,council,of,approval"},
  {"love_left", "♥(ˆ⌣ˆԅ)", "love_left,love,like,love left,smile"},
  {"sleeping", "(´-ω-)´_ _)´-ω-)´_ _)zZZ", "sleeping,good night,night,sleepy"},
  {"frog_eating_a_fly", "8)~~~~~ *", "frog_eating_a_fly,frog,eating,a,fly"},
  {"pup", "ᶘ ◕ᴥ◕ᶅ", "pup,pup"},
  {"kawaï", "∩( ・ω・)∩", "kawaï,kawaï"},
  {"trumpet", "-=iii=<()", "trumpet,trumpet"},
  {"crying", "੨( ･᷄ ︵･᷅ )ｼ", "crying,cry,depressed,unhappy"},
  {"magic_flower", "(⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿", "magic_flower,majic,give_you,beautiful"},
  {"poking", "（￢з￢）σ", "poking,poke,heyhey"},
  {"simple_cat", "=^._.^= ∫", "simple_cat,cat,animal,nya,meow,simple,pet"},
  {"drunkenness", "ヽ（´ー｀）┌", "drunkenness,drunkenness"},
  {"bear", "ˁ(⦿ᴥ⦿)ˀ", "bear,bear"},
  {"flower_power", "ヽ(·̿̿Ĺ̯̿̿·̿✿)ﾉ", "flower_power,flower,power"},
  {"middle_fingers", "┌∩┐(◣ _ ◢)┌∩┐", "middle_fingers,middle,fingers"},
  {"bear_replacing_table", "┬─┬ ノʕ•ᴥ•ノʔ", "bear_replacing_table,bear,replacing,table"},
  {"angry_shrug", "¯\\_| ಠ ∧ ಠ |_/¯", "angry_shrug,angry,shrug"},
  {"hugs", "(っ◕‿◕)っ", "hugs,hugs"},
  {"monkey", "@(_)@", "monkey,monkey"},
  {"sword", "@xxxx[{::::::::::::::>", "sword,sword"},
  {"upside_down_lenny", "( ͜。 ͡ʖ ͜。)", "upside_down_lenny,upside,down,lenny"},
  {"crying_2", "(╥﹏╥)", "crying_2,crying"},
  {"domino", "[: :|:::]", "domino,domino"},
}